unstable_features = true
# imports_layout = "Vertical"
imports_granularity = "crate"
max_width = 120
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
format_strings = true
version = "Two"
